<a href="https://colab.research.google.com/github/ekanshtrivedi/class-work/blob/master/NNJ066.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.seed(1)
X_axes=np.random.randn(2,3)
Y_axes=(np.random.randn(1,3,)>0)

In [3]:
print(X_axes)
print(Y_axes)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
[[ True False  True]]


In [4]:
def layer_sizes(X,Y):
  n_x=X.shape[0]
  n_h=4
  n_y=Y.shape[0]
  return n_x,n_h,n_y

In [5]:
def initialize_parameters(n_x,n_h,n_y):
  np.random.seed(2)
  W1=np.random.randn(n_h,n_x)*0.01
  b1=np.zeros(shape=(n_h,1))
  W2=np.random.randn(n_y,n_h)*0.01
  b2=np.zeros(shape=(n_y,1))
  parameters={"W1":W1,"b1":b1,"W2":W2,"b2":b2}
  return parameters


In [6]:
n_x,n_h,n_y=2,4,1
parameters=initialize_parameters(n_x,n_h,n_y)

In [7]:
def sigmoid(z):
  a=1/(1+np.exp(-z))
  return a

In [8]:
def forward_propagation(X, parameters):
    
    W1 = parameters['W1']
    b1 = parameters['b1']
    W2 = parameters['W2']
    b2 = parameters['b2']
    
    # Implement Forward Propagation to calculate A2 (probabilities)
    
    Z1 = np.dot(W1, X) + b1
    A1 = np.tanh(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)
    
    
    
    cache = {"Z1": Z1, "A1": A1, "Z2": Z2, "A2": A2}
    
    return A2, cache

In [9]:
A2,parameter=forward_propagation(X_axes,parameters)

In [10]:
print("A2: "+str(A2))
print("Z1: " + str(parameter["Z1"]))
print("A1: " + str(parameter["A1"]))
print("Z2: " + str(parameter["Z2"]))
print("A2: " + str(parameter["A2"]))

A2: [[0.5002307  0.49985831 0.50023963]]
Z1: [[-0.00616586  0.00206261  0.0034962 ]
 [-0.05229879  0.02726335 -0.02646868]
 [-0.0200999   0.00368691  0.02884556]
 [ 0.02153008 -0.01385323  0.02600471]]
A1: [[-0.00616578  0.0020626   0.00349619]
 [-0.05225116  0.02725659 -0.0264625 ]
 [-0.0200972   0.00368689  0.02883756]
 [ 0.02152676 -0.01385234  0.02599885]]
Z2: [[ 0.00092281 -0.00056678  0.00095853]]
A2: [[0.5002307  0.49985831 0.50023963]]


In [11]:
def compute_cost(A2, Y, parameters):
        
    m = Y.shape[1] 
    
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    cost=-np.sum(Y*np.log(A2)+(1-Y)*np.log(1-A2))/m
      
    cost = np.squeeze(cost)     
    assert(isinstance(cost, float))
    
    return cost

In [12]:
cost=compute_cost(A2,Y_axes,parameters)
print(cost)

0.6927392477233995


In [13]:
def backward_propagation(parameters,cache,X,Y):
  m=X.shape[1]
  W1=parameters["W1"]
  b1=parameters["b1"]
  W2=parameters["W2"]
  b2=parameters["b2"]
  A2=cache["A2"]
  A1=cache["A1"]

  dZ2=A2-Y
  dW2=np.dot(dZ2,A1.T)/m
  db2=np.sum(dZ2,axis=1,keepdims=True)/m
  dZ1=np.dot(W2.T,dZ2)*(1-np.power(A1,2))
  dW1=np.dot(dZ1,X.T)/m
  db1=np.sum(dZ1,axis=1,keepdims=True)/m

  grads={"dW1":dW1,"db1":db1,"dW2":dW2,"db2":db2}

  return grads

In [14]:
grads=backward_propagation(parameters,parameter,X_axes,Y_axes)

In [15]:
grads

{'dW1': array([[ 0.00301023, -0.00747267],
        [ 0.00257968, -0.00641288],
        [-0.00156892,  0.003893  ],
        [-0.00652037,  0.01618243]]),
 'dW2': array([[ 0.00078841,  0.01765429, -0.00084166, -0.01022527]]),
 'db1': array([[ 0.00176201],
        [ 0.00150995],
        [-0.00091736],
        [-0.00381422]]),
 'db2': array([[-0.16655712]])}

In [16]:
def update_parameters(parameters,grads,lr=1.2):
  W1=parameters["W1"]
  b1=parameters["b1"]
  W2=parameters["W2"]
  b2=parameters["b2"]

  dW1=grads["dW1"]
  db1=grads["db1"]
  dW2=grads["dW2"]
  db2=grads["db2"]

  W1=W1-lr*dW1
  W2=W2-lr*dW2
  b1=b1-lr*db1
  b2=b2-lr*db2

  parameters={"W1":W1,"b1":b1,"W2":W2,"b2":b2}

  return parameters



In [17]:
parameters=update_parameters(parameters,grads,lr=1.2)

In [18]:
parameters

{'W1': array([[-0.00777986,  0.00840453],
        [-0.02445757,  0.02409817],
        [-0.01605165, -0.01308908],
        [ 0.01285325, -0.0318718 ]]),
 'W2': array([[-0.01152561, -0.03027522,  0.00652453,  0.03519241]]),
 'b1': array([[-0.00211442],
        [-0.00181194],
        [ 0.00110084],
        [ 0.00457706]]),
 'b2': array([[0.19986854]])}

In [23]:
def nn_model(X,Y,n_h,num_itr=100000,print_cost=False):
 
  np.random.seed(3)
  n_x=layer_sizes(X,Y)[0]
  n_y=layer_sizes(X,Y)[2]
 
  parameters = initialize_parameters(n_x, n_h, n_y)
 
  for i in range(0, num_itr):
    A2,cache=forward_propagation(X,parameters)
 
    cost=compute_cost(A2,Y,parameters)
 
    grads=backward_propagation(parameters,cache,X,Y)
 
    parameters=update_parameters(parameters,grads,lr=1.2)
 
    if print_cost and i % 1000 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))


 
  return parameters


In [24]:
parameters=nn_model(X_axes,Y_axes,n_h=4,num_itr=100000,print_cost=True)
parameters

Cost after iteration 0: 0.692739
Cost after iteration 1000: 0.000218
Cost after iteration 2000: 0.000107
Cost after iteration 3000: 0.000071
Cost after iteration 4000: 0.000053
Cost after iteration 5000: 0.000042
Cost after iteration 6000: 0.000035
Cost after iteration 7000: 0.000030
Cost after iteration 8000: 0.000026
Cost after iteration 9000: 0.000023
Cost after iteration 10000: 0.000021
Cost after iteration 11000: 0.000019
Cost after iteration 12000: 0.000018
Cost after iteration 13000: 0.000016
Cost after iteration 14000: 0.000015
Cost after iteration 15000: 0.000014
Cost after iteration 16000: 0.000013
Cost after iteration 17000: 0.000012
Cost after iteration 18000: 0.000012
Cost after iteration 19000: 0.000011
Cost after iteration 20000: 0.000011
Cost after iteration 21000: 0.000010
Cost after iteration 22000: 0.000010
Cost after iteration 23000: 0.000009
Cost after iteration 24000: 0.000009
Cost after iteration 25000: 0.000008
Cost after iteration 26000: 0.000008
Cost after ite

{'W1': array([[-0.72808556,  1.34225268],
        [-0.81651504,  1.49065275],
        [ 0.6615354 , -1.24757561],
        [ 0.82117678, -1.50887831]]),
 'W2': array([[-3.01587153, -3.83903168,  2.55943921,  3.93699737]]),
 'b1': array([[ 0.32715657],
        [ 0.38318796],
        [-0.28863399],
        [-0.38918499]]),
 'b2': array([[0.20815629]])}